### ISSUE TITLE
conflict while pushing the changes to main branch

### ISSUE THREAD

**Issue by AasthaBabbar** [obaonikoyi/Tafe20S210b#1]
Failed to push some refs
![image](https://user-images.githubusercontent.com/70680419/94180714-98065200-fedd-11ea-90cb-a034dc861744.png)

**Comment by AasthaBabbar** [comment]
Closed the issue by clicking pull to merge main branch changes as well
![image](https://user-images.githubusercontent.com/70680419/94180843-c4ba6980-fedd-11ea-9882-cef24e7efb4b.png)

**Comment by obaonikoyi** [comment]
It hasn't been merged yet
![image](https://user-images.githubusercontent.com/70100105/94341065-ab343180-0045-11eb-8a66-1d6293d9e9fc.png)
![image](https://user-images.githubusercontent.com/70100105/94341003-39f47e80-0045-11eb-8813-6be83a7ecb46.png)

**Comment by obaonikoyi** [comment]
I have merged it
![image](https://user-images.githubusercontent.com/70100105/94341179-9efca400-0046-11eb-8caa-f9077864c13d.png)
